# Generated by Django 5.2 on 2025-05-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_flashcard_flashcardsession_flashcardreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertokenusage",
            name="max_tokens",
            field=models.IntegerField(default=25000),
        ),
    ]
