# Generated by Django 5.2 on 2025-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_usertokenusage_max_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="total_questions",
            field=models.IntegerField(default=0),
        ),
    ]
