# Generated by Django 5.2 on 2025-05-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_quizsession_total_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="correct_answers",
            field=models.IntegerField(default=0),
        ),
    ]
