# Generated by Django 5.1.7 on 2025-08-25 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_quizsession_correct_answers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mnemonic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mnemonic", models.TextField()),
                (
                    "mnemonic_type",
                    models.CharField(
                        choices=[
                            ("acronym", "Acronym"),
                            ("acrostic", "Acrostic"),
                            ("rhyme", "Rhyme"),
                            ("association", "Association"),
                            ("visualization", "Visualization"),
                        ],
                        default="acronym",
                        max_length=20,
                    ),
                ),
                ("mnemonic_explanation", models.TextField()),
                ("topic", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mnemonics",
                        to="api.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mnemonics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mnemonics",
            },
        ),
    ]
