# Generated by Django 5.1.7 on 2025-08-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_mnemonic"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizanswer",
            name="time_taken",
            field=models.FloatField(
                default=0.0,
                help_text="Time taken to answer in seconds",
            ),
            preserve_default=False,
        ),
    ]
