# Generated by Django 5.1.7 on 2025-08-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_quizanswer_time_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_mastery_score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="document",
            name="next_review_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="review_interval_days",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="quiz",
            name="mastery_score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
