# Generated by Django 5.1.7 on 2025-08-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_document_document_mastery_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="AI-generated summary of the document content",
                null=True,
            ),
        ),
    ]
