# Generated by Django 5.1.7 on 2025-08-31 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_document_summary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="AI-generated summary of the document content for quick overview",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("daily_study_hours", models.FloatField()),
                ("days_until_exam", models.IntegerField()),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("essay", "Essay"),
                            ("short_answer", "Short Answer"),
                            ("practical", "Practical"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                ("additional_context", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("total_study_hours", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exam_date", models.DateField()),
                (
                    "documents",
                    models.ManyToManyField(
                        related_name="study_plans", to="api.document"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "study_plans",
            },
        ),
        migrations.CreateModel(
            name="StudyPlanStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
                ("step_order", models.IntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("reading", "Reading"),
                            ("video", "Video"),
                            ("quiz", "Quiz"),
                            ("flashcards", "Flashcards"),
                            ("mnemonics", "Mnemonics"),
                            ("review", "Review"),
                            ("practice", "Practice"),
                        ],
                        default="reading",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High Priority"),
                            ("medium", "Medium Priority"),
                            ("low", "Low Priority"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("topic", models.CharField(max_length=255)),
                ("estimated_duration", models.FloatField()),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("quiz_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.document",
                    ),
                ),
                (
                    "study_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="api.studyplan",
                    ),
                ),
            ],
            options={
                "db_table": "study_plan_steps",
                "ordering": ["day_number", "step_order"],
                "unique_together": {("study_plan", "day_number", "step_order")},
            },
        ),
        migrations.CreateModel(
            name="StudyPlanResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube Video"),
                            ("article", "Article"),
                            ("blog", "Blog Post"),
                            ("website", "Website"),
                            ("pdf", "PDF Document"),
                            ("other", "Other"),
                        ],
                        default="article",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                ("estimated_duration", models.FloatField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "study_plan_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="api.studyplanstep",
                    ),
                ),
            ],
            options={
                "db_table": "study_plan_resources",
                "ordering": ["created_at"],
            },
        ),
    ]
